language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  # - npm run test-headless
  - ng build --prod --base-href https://dheeraj237.github.io/worvy-ui/
  - mv dist/worvy-ui/index.html dist/worvy-ui/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/worvy-ui
  on:
    branch: master
notifications:
  email:
    recipients:
      - dheerusuthar@gmail.com
    on_success: always
    on_failure: always
